title: Cairn
permalink: pretty
remote_theme: pmarsceill/just-the-docs
site.url: https://fedemame.github.io/cairn-ita
logo: "/img/logo.svg"
color_scheme: dark
encoding: UTF-8
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
include:
  - js

# Back to top link
back_to_top: true
back_to_top_text: "Torna su"

footer_content: "Il testo presente in questa pagina è sotto licenza <a href=\"https://creativecommons.org/licenses/by-sa/4.0\">CC-BY-SA 4.0.</a>"
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
